# Pipeline Process Rakefile

import '../lib/tasks/log.rake'

task :default => [ :pdfocr ]

task :create_instances do
  log 'creating pdftk instance'
  sh 'sudo docker create --name=piper.pdftk edhowland/pdftk:v0.1 date'
  log 'creating pdfocr instance'
end

task :pdftk => :create_instances do
  log 'Starting pdftk instance'
end

task :pdfocr => :pdftk do
  log 'Starting pdfocr instance'
end

task :destroy_instances do
  log 'Destroying pdftk'
  sh 'sudo docker rm piper.pdftk'
end
